[package]
name = "rust"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "d01p1"
path = "src/d01p1.rs"

[[bin]]
name = "d01p2"
path = "src/d01p2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
